fix some build errors since Linux 5.7
when i run `make`, these errors came out like this:
cd SOURCE/module; make --jobs=12
make[1]: Entering directory '/home/ubuntu/workspace/diagnose-tools/SOURCE/module'
make CFLAGS_MODULE="-DMODULE " -C /lib/modules/5.8.0-40-generic/build M=/home/ubuntu/workspace/diagnose-tools/SOURCE/module modules
make[2]: Entering directory '/usr/src/linux-headers-5.8.0-40-generic'

  CC [M]  /home/ubuntu/workspace/diagnose-tools/SOURCE/module/symbol.o
/home/ubuntu/workspace/diagnose-tools/SOURCE/module/pub/trace_file.c: In function ‘traverse’:
/home/ubuntu/workspace/diagnose-tools/SOURCE/module/pub/trace_file.c:115:3: error: ‘struct seq_file’ has no member named ‘version’
  115 |  m->version = 0;
      |   ^~
/home/ubuntu/workspace/diagnose-tools/SOURCE/module/pub/trace_file.c: In function ‘__seq_read’:

this error is intorduced by this commit: b829a0f0f2f2("seq_file: remove m->version").
We can add some version macros to avoid this build error.

Add some ignore file to .gitignore and add some make clean targets by the way.

Signed-off-by: Hui Su <sh_def@163.com>